name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        pip3 install --user -r requirements.txt
    - name: Build the docs
      run: which sphinx-build
