name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        pip3 install --user -r requirements.txt
    - name: Build the docs
      run: |
        export PATH="$HOME/.local/bin:$PATH"
        make html
        mv _build/html $HOME/output
        cd $HOME/output
        git config --global user.email "kevin.putnam@intel.com"
        git config --global user.name "Kevin Putnam"
        git init
        git add .
        git commit -m "latest html output"